OMAP: Fix missing usb.h include
Without this, we get the following build error:

drivers/usb/musb/musb_dsps.c: In function 'musb_dsps_phy_control':
drivers/usb/musb/musb_dsps.c:156:18: error: 'USBPHY_CM_PWRDN' undeclared (first use in this function)
drivers/usb/musb/musb_dsps.c:156:18: note: each undeclared identifier is reported only once for each function it appears in
drivers/usb/musb/musb_dsps.c:156:36: error: 'USBPHY_OTG_PWRDN' undeclared (first use in this function)
drivers/usb/musb/musb_dsps.c:157:16: error: 'USBPHY_OTGVDET_EN' undeclared (first use in this function)
drivers/usb/musb/musb_dsps.c:157:36: error: 'USBPHY_OTGSESSEND_EN' undeclared (first use in this function)

Signed-off-by: Alexander Graf <agraf@suse.de>